docs/src/site-preprocess/index.md

This threw me off a bit while evaluating the library as I need 2.12 support

Mention support for scala 2.12 in the docs

---

docs/src/site-preprocess/index.md

#93: Fix link to latest version in companion site

---

codecov.yml

[97] Disable codecov comments

---

build.sbt
docs/src/main/tut/bom.md
docs/src/main/tut/refined.md
docs/src/site-preprocess/index.md
refined/src/main/scala/kantan/csv/refined/package.scala
refined/src/test/scala/kantan/csv/refined/RefinedCodecTests.scala
refined/src/test/scala/kantan/csv/refined/arbitrary.scala

Implement a refined module

---

index.md

Fix a link to benchmark page

---

index.md

Reverts nrinaudo/kantan.csv#113

Revert "Fix a link to benchmark page"

---

project/build.properties
project/plugins.sbt

Fixes #117
Note that this currently fails as kantan.sbt 2.0.0 is not yet available publicly.

WIP: [#117] Update to kantan.sbt 2.0.0

---

project/Versions.scala
refined/src/main/scala/kantan/csv/refined/package.scala

[#119] Update to the new Refined instances

---

build.sbt
docs/src/main/tut/bom.md
docs/src/main/tut/enumeratum.md
enumeratum/src/main/scala/kantan/csv/enumeratum/package.scala
enumeratum/src/main/scala/kantan/csv/enumeratum/values/package.scala
enumeratum/src/test/scala/kantan/csv/enumeratum/EnumCodecTests.scala
enumeratum/src/test/scala/kantan/csv/enumeratum/arbitrary.scala
enumeratum/src/test/scala/kantan/csv/enumeratum/values/ByteEnumCodecTests.scala
enumeratum/src/test/scala/kantan/csv/enumeratum/values/CharEnumCodecTests.scala
enumeratum/src/test/scala/kantan/csv/enumeratum/values/IntEnumCodecTests.scala
enumeratum/src/test/scala/kantan/csv/enumeratum/values/LongEnumCodecTests.scala
enumeratum/src/test/scala/kantan/csv/enumeratum/values/ShortEnumCodecTests.scala
enumeratum/src/test/scala/kantan/csv/enumeratum/values/StringEnumCodecTests.scala

[#116] Add an enumeratum module

---

.travis.yml

[#108] Clean-up travis JDKs

---

generic/src/main/scala/kantan/csv/generic/GenericInstances.scala

[#124] Drop unnecessary Decoder[CNil] instances

---

core/src/main/boilerplate/kantan/csv/GeneratedHeaderDecoders.scala.template
core/src/main/boilerplate/kantan/csv/GeneratedRowCodecs.scala.template
core/src/main/boilerplate/kantan/csv/GeneratedRowDecoders.scala.template
core/src/main/boilerplate/kantan/csv/TupleInstances.scala.template
core/src/main/scala/kantan/csv/CellDecoder.scala
core/src/main/scala/kantan/csv/CellEncoder.scala
core/src/main/scala/kantan/csv/CsvSink.scala
core/src/main/scala/kantan/csv/CsvSource.scala
core/src/main/scala/kantan/csv/DecodeResult.scala
core/src/main/scala/kantan/csv/ParseResult.scala
core/src/main/scala/kantan/csv/RowDecoder.scala
core/src/main/scala/kantan/csv/ops/CsvCellDecoderOps.scala
core/src/main/scala/kantan/csv/ops/CsvCellEncoderOps.scala
core/src/main/scala/kantan/csv/ops/CsvRowDecoderOps.scala
core/src/main/scala/kantan/csv/ops/CsvRowEncoderOps.scala
core/src/main/scala/kantan/csv/ops/CsvRowReadingOps.scala
core/src/main/scala/kantan/csv/ops/CsvRowWritingOps.scala
core/src/main/scala/kantan/csv/ops/CsvRowsOps.scala
core/src/main/scala/kantan/csv/ops/CsvSourceOps.scala

[#126] Use @example for doctest examples

---

build.sbt
core/src/main/boilerplate/kantan/csv/GeneratedHeaderDecoders.scala.template
core/src/main/boilerplate/kantan/csv/GeneratedRowCodecs.scala.template
core/src/main/boilerplate/kantan/csv/GeneratedRowDecoders.scala.template
core/src/main/boilerplate/kantan/csv/TupleInstances.scala.template
core/src/main/scala/kantan/csv/CellDecoder.scala
core/src/main/scala/kantan/csv/CsvReader.scala
core/src/main/scala/kantan/csv/CsvSink.scala
core/src/main/scala/kantan/csv/CsvSource.scala
core/src/main/scala/kantan/csv/DecodeResult.scala
core/src/main/scala/kantan/csv/HeaderDecoder.scala
core/src/main/scala/kantan/csv/ParseResult.scala
core/src/main/scala/kantan/csv/RowDecoder.scala
core/src/main/scala/kantan/csv/engine/ReaderEngine.scala
core/src/main/scala/kantan/csv/ops/CsvCellDecoderOps.scala
core/src/main/scala/kantan/csv/ops/CsvRowDecoderOps.scala
core/src/main/scala/kantan/csv/ops/CsvRowReadingOps.scala
core/src/main/scala/kantan/csv/ops/CsvSourceOps.scala
core/src/main/scala/kantan/csv/package.scala
core/src/test/scala/kantan/csv/DecodeResultTests.scala
core/src/test/scala/kantan/csv/ParseResultTests.scala
core/src/test/scala/kantan/csv/ops/CsvSourceOpsTests.scala
docs/src/main/tut/cats.md
docs/src/main/tut/csv_sources.md
docs/src/main/tut/error_handling.md
docs/src/main/tut/scalaz.md
docs/src/main/tut/step_by_step_parsing.md
generic/src/main/scala/kantan/csv/generic/GenericInstances.scala
scalaz/src/main/scala/kantan/csv/scalaz/package.scala

[#128] Replace Result by Either

---

cats/src/main/scala/kantan/csv/cats/package.scala
cats/src/test/scala/kantan/csv/cats/CodecTests.scala
cats/src/test/scala/kantan/csv/cats/ErrorTests.scala
cats/src/test/scala/kantan/csv/cats/FoldableEncoderTests.scala
cats/src/test/scala/kantan/csv/cats/equality.scala
docs/src/main/tut/cats.md
laws/src/main/scala/kantan/csv/laws/Cell.scala
laws/src/main/scala/kantan/csv/laws/discipline/arbitrary.scala

[#131] Improve Cats instances

---

laws/src/main/scala/kantan/csv/laws/discipline/arbitrary.scala

[#135] Use provided Arbitrary instances for Decoder and Encoder

---

build.sbt
docs/src/main/tut/bom.md
docs/src/main/tut/index.md
docs/src/main/tut/libra.md
libra/src/main/scala/kantan/csv/libra/package.scala
libra/src/test/scala/kantan/csv/libra/LibraCodecTests.scala
libra/src/test/scala/kantan/csv/libra/arbitrary.scala

[#137] Implement a libra module

---

docs/src/main/tut/scalaz.md
scalaz/src/main/scala/kantan/csv/scalaz/package.scala
scalaz/src/test/scala/kantan/csv/scalaz/CodecTests.scala
scalaz/src/test/scala/kantan/csv/scalaz/ErrorTests.scala
scalaz/src/test/scala/kantan/csv/scalaz/FoldableEncoderTests.scala
scalaz/src/test/scala/kantan/csv/scalaz/equality.scala

[#140] Improve Scalaz instances

---

build.sbt

[#142] Remove lambda deserialisation workaround

---

scalaz/shared/src/test/scala/kantan/csv/scalaz/DisjunctionCodecTests.scala
scalaz/shared/src/test/scala/kantan/csv/scalaz/MaybeCodecTests.scala

[#148] Stop using ScalazArbitrary

---

core/shared/src/main/scala/kantan/csv/DecodeResult.scala

[#150] Replace WithDefault by WithError

---

java8/src/main/scala/kantan/csv/java8/package.scala
joda-time/src/main/scala/kantan/csv/joda/time/package.scala

[#152] Update the time modules' documentation

---

docs/src/main/tut/data_as_collection.md
docs/src/main/tut/engines.md
docs/src/main/tut/error_handling.md
docs/src/main/tut/rows_as_collections.md
docs/src/main/tut/rows_as_tuples.md
docs/src/main/tut/step_by_step_parsing.md

[#130] Fix broken links in documentation

---

docs/src/main/tut/java8.md
docs/src/main/tut/joda_time.md
java8/src/main/scala/kantan/csv/java8/package.scala
joda-time/src/main/scala/kantan/csv/joda/time/package.scala

[#155] Add support for literal date formats

---

docs/src/main/tut/case_classes_as_rows.md
docs/src/main/tut/rows_as_case_classes.md

[#112] Add libraryDependencies instructions to shapeless doc

---

.travis.yml
docs/src/main/tut/libra.md
project/Versions.scala
project/build.properties
project/plugins.sbt

[#166] Update to Scala 2.12.6

---

docs/src/main/mdoc/arbitrary_types_as_cells.md
docs/src/main/mdoc/arbitrary_types_as_rows.md
docs/src/main/mdoc/bom.md
docs/src/main/mdoc/case_classes_as_rows.md
docs/src/main/mdoc/cats.md
docs/src/main/mdoc/cells_as_arbitrary_types.md
docs/src/main/mdoc/codecs.md
docs/src/main/mdoc/collections_as_rows.md
docs/src/main/mdoc/csv_sinks.md
docs/src/main/mdoc/csv_sources.md
docs/src/main/mdoc/data_as_collection.md
docs/src/main/mdoc/default_instances.md
docs/src/main/mdoc/engines.md
docs/src/main/mdoc/enumeratum.md
docs/src/main/mdoc/error_handling.md
docs/src/main/mdoc/headers.md
docs/src/main/mdoc/java8.md
docs/src/main/mdoc/libra.md
docs/src/main/mdoc/refined.md
docs/src/main/mdoc/rows_as_arbitrary_types.md
docs/src/main/mdoc/rows_as_case_classes.md
docs/src/main/mdoc/rows_as_collections.md
docs/src/main/mdoc/rows_as_tuples.md
docs/src/main/mdoc/scalaz.md
docs/src/main/mdoc/serialising_collections.md
docs/src/main/mdoc/shapeless.md
docs/src/main/mdoc/step_by_step_parsing.md
docs/src/main/mdoc/step_by_step_serialisation.md
docs/src/main/mdoc/tuples_as_rows.md

[#195] Fix layout issues that broke links in the documentation site

---

build.sbt

[#202] Fix JMH profiling useless benchmarks

---

commons/src/test/scala/kantan/csv/engine/commons/CommonsWriterTests.scala
jackson/src/test/scala/kantan/csv/engine/jackson/JacksonReaderTests.scala
jackson/src/test/scala/kantan/csv/engine/jackson/JacksonWriterTests.scala

This will be necessary when upgrading to discipline-scalatest 1.0.1

Unify discipline usage

---

cats/shared/src/test/scala/kantan/csv/cats/ErrorTests.scala
core/shared/src/test/scala/kantan/csv/DecodeResultTests.scala
core/shared/src/test/scala/kantan/csv/ParseResultTests.scala
core/shared/src/test/scala/kantan/csv/ops/CsvSourceOpsTests.scala
scalaz/shared/src/test/scala/kantan/csv/scalaz/ErrorTests.scala

- same as https://github.com/nrinaudo/kantan.codecs/pull/397

add parentheses. prepare Scala 3
